### ISSUE TITLE
Italian Language

### ISSUE THREAD

**Issue by Druskus** [Kicktemp/kickgdpr#3]
I know that this is not a issue, but I am unable to open requests.

I Have Translate this plugin in italian, is it possible to insert the translation in the official branch? For Download Plugin and translation (Version 2.4.0) here:

http://www.joomla.it/download-della-community/download/4-file-lingua-di-estensioni/130-traduzione-italiana-kick-gdpr.html

Thank You

**Comment by tecpromotion** [comment]
Hello @Druskus 

Thank you for your request and work in the translation.
We are currently planning the next steps and we expect to have a Pro version in the future. Therefore, it is not possible to include the translation in the official branch. At least not until we have clarified everything internally.

What I can well imagine is a link to the Italian translation to install. It should be the pure translation of the plugin, because it can sometimes give a hot or security fix.
Would it be okay for you?

**Comment by tecpromotion** [comment]
Thanks @Druskus
